app/cars/urls.py
from django.urls import path
from .views import (
    HomePageView, 
    CarListView, 
    CarDetailView, 
    CarCreateView, 
    CarUpdateView, 
    CarDeleteView, 
    mark_car_as_not_sold
)

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),  
    path('cars/', CarListView.as_view(), name='car_list'),
    path('cars/<int:pk>/', CarDetailView.as_view(), name='car_detail'),
    path('cars/new/', CarCreateView.as_view(), name='car_new'),
    path('cars/<int:pk>/edit/', CarUpdateView.as_view(), name='car_edit'),
    path('cars/<int:pk>/delete/', CarDeleteView.as_view(), name='car_delete'),
    path('cars/<int:car_id>/mark_not_sold/', mark_car_as_not_sold, name='mark_car_not_sold'),
]

app/dealership/urls.py
from django.contrib import admin
from django.urls import path, include # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls')), # new 
    path('', include('salespeople.urls')), # new
]

app/cars/models.py
from django.utils import timezone
from django.db import models
from django.forms import ValidationError
import string
import random

class Car(models.Model):
    """
    Model for Car instances.
    
    A Car instance represents a car in the inventory. It contains information
    about the car, including the make, model, year, color, price, mileage,
    whether or not it is sold and a vehicle identification number. If it is sold, the date sold and the salesperson who sold it are also included.
    
    Attributes:
        make: A string representing the make of the car.
        model: A string representing the model of the car.
        year: An integer representing the year the car was made.
        color: A string representing the color of the car.
        price: An integer representing the price of the car.
        mileage: An integer representing the mileage of the car.
        sold: A boolean representing whether or not the car is sold.
        date_sold: A date representing the date the car was sold.
        salesperson: A Salesperson instance representing the salesperson who sold
            the car.
        vin: A string representing the VIN of the car.
        
    Methods:
        calculate_commission: Calculates the commission for the car.
        formatted_mileage: Returns the mileage of the car as a string with
            thousands separators.
        formatted_price: Returns the price of the car as a string with thousands
            separators.
        mark_as_not_sold: Marks the car as not sold.
        clean: Validates the Car instance.
        save: Saves the Car instance.
    """

    make = models.CharField(max_length=12, blank=False, null=False)
    model = models.CharField(max_length=12, blank=False, null=False)
    year = models.IntegerField(blank=False, null=False)
    # color = models.CharField(max_length=20, blank=False, null=False)
    price = models.IntegerField(blank=False, null=False)
    mileage = models.IntegerField(blank=True, null=True)
    sold = models.BooleanField(default=False)
    date_sold = models.DateField(blank=True, null=True)
    salesperson = models.ForeignKey('salespeople.Salespeople', on_delete=models.SET_NULL, null=True, blank=True, related_name='sold_cars')
    vin = models.CharField(max_length=17, unique=True, blank=True) 

    """ Car Colors """
    BLACK = 'Black'
    BLUE = 'Blue'
    BROWN = 'Brown'
    GOLD = 'Gold'
    GREEN = 'Green'
    GREY = 'Grey'
    ORANGE = 'Orange'
    RED = 'Red'
    SILVER = 'Silver'
    WHITE = 'White'
    CAR_COLOR_CHOICES = [
        (BLACK, 'Black'),
        (BLUE, 'Blue'),
        (BROWN, 'Brown'),
        (GOLD, 'Gold'),
        (GREEN, 'Green'),
        (GREY, 'Grey'),
        (ORANGE, 'Orange'),
        (RED, 'Red'),
        (SILVER, 'Silver'),
        (WHITE, 'White'),
    ]

    car_color = models.CharField(max_length=15, choices=CAR_COLOR_CHOICES, default=BLACK)


    """ Car Type """
    CONVERTIBLE = 'Convertible'
    COUPE = 'Coupe'
    HATCHBACK = 'Hatchback'
    SEDAN = 'Sedan'
    SUV = 'SUV'
    TRUCK = 'Truck'
    WAGON = 'Wagon'
    CAR_TYPE_CHOICES = [
        (CONVERTIBLE, 'Convertible'),
        (COUPE, 'Coupe'),
        (SEDAN, 'Sedan'),
        (SUV, 'SUV'),
        (TRUCK, 'Truck'),
    ]
    car_type = models.CharField(max_length=15, choices=CAR_TYPE_CHOICES, default=SEDAN)

    COMMISSION_RATE = 0.20 # 20% commission rate

    def calculate_commission(self):
        """ Calculates the commission of the car and rounds it to two decimal places."""
        commission =  self.price * self.COMMISSION_RATE
        return round(commission, 2)

    def _generate_vin(self):
        """
        Generates a random 17-character string that simulates a VIN, which is used to uniquely
        identify vehicles. Please note that this is a simplified example for demonstration purposes
        and doesn't adhere to actual VIN standards.

        Args:
            self: An instance of the Car class.

        Returns:
            vin(str): A string representing the VIN of the car.
        """
        return ''.join(random.choices(string.ascii_uppercase + string.digits, k=17))
    
    def formatted_mileage(self):
        return "{:,}".format(self.mileage)
    
    def formatted_price(self):
        return "{:,.2f}".format(self.price)
    
    def mark_as_not_sold(self):
        """
        Sets a previously sold car's sold attribute to false, sets the salesperson attribute to None and saves the car instance when the user marks the car as not sold.
        
        Args:
            self: An instance of the Car class.
            
        Returns:
            None
        """
        self.sold = False
        self.salesperson = None  # Set the salesperson to None
        self.save()

    def clean(self):
        """
        Validate the attributes of a Car instance before saving it to the database.
        It checks for various validation rules and raises ValidationErrors if any of the rules are violated.

        Validation Rules:
        1. Car Existence Check:
            - Checks if a car with the same make, model, year, color, mileage, and car_type already exists in the database.
            - Uses iexact operator to make a case-insensitive comparison of the make, model, and color.
            - If a duplicate car is found (excluding the current instance by its ID), it raises a ValidationError.

        2. Sold Car Validation:
            - If the 'sold' attribute is True, it checks for the presence of 'date_sold' and 'salesperson'.
            - If 'date_sold' or 'salesperson' is missing when a car is marked as sold, it raises a ValidationError.

        3. Salesperson Assignment Validation:
            - If a 'salesperson' is assigned to the car, it checks for the presence of 'date_sold' and 'sold' status.
            - If 'date_sold' or 'sold' status is missing when a salesperson is assigned, it raises a ValidationError.

        4. Sale Date Validation:
            - If a 'date_sold' is specified, it checks for the presence of 'salesperson' and 'sold' status.
            - If 'salesperson' or 'sold' status is missing when a sale date is set, it raises a ValidationError.
            - It also checks if the 'date_sold' is not in the future. If it is, it raises a ValidationError.

        Args:
            self: An instance of the Car class.

        Raises:
            ValidationError: If any of the validation rules are violated.
        """
        if self.make and self.model and self.year and self.car_color and self.mileage:
            if Car.objects.filter(make__iexact=self.make, model__iexact=self.model, year=self.year, car_color=self.car_color, mileage=self.mileage, car_type=self.car_type).exclude(id=self.id).exists():
                raise ValidationError("Car already exists")
            
        if self.sold and (not self.date_sold or not self.salesperson):
            raise ValidationError("Date sold and salesperson are required when the car is sold.")

        if self.salesperson and (not self.date_sold or not self.sold):
            raise ValidationError("Sold status and date sold are required when a Salesperson is assigned.")

        if self.date_sold and (not self.salesperson or not self.sold):
            raise ValidationError("Sold status and Salesperson are required when a sale date is set.")
        
        #make sure date_sold is not in the future
        if self.date_sold and self.date_sold > timezone.now().date():
            raise ValidationError("Date sold cannot be in the future.")
    
    def save(self, *args, **kwargs):
        """
        This method is used to save the Car instance to the database. It follows these steps:
            - The clean() method is called to validate the Car instance before saving.
            - If the 'vin' field is empty, a VIN is generated.
            - The 'make' and 'model' fields are capitalized for consistency.
            - Finally, the Car instance is saved to the database.

        Args:
            self: An instance of the Car class.
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
            
        Returns:
            None
        """
        self.clean()
        if not self.vin:
            self.vin = self._generate_vin()

        def custom_title(s):
            special_cases = {"Mach-e": "Mach-E"}  # Add more special cases as needed
            words = s.split()
            titled_words = [special_cases.get(word.lower(), word.title()) for word in words]
            return ' '.join(titled_words)

        for field_name in ['make', 'model']:
            val = getattr(self, field_name, "").strip()
            # accounts for BMW, GMC, etc.
            if len(val) == 3:
                setattr(self, field_name, val.upper())
            else:
                setattr(self, field_name, custom_title(val))

        super(Car, self).save(*args, **kwargs)

    def __str__(self):
        """ Returns a string representation of the Car instance. """
        return f'{self.vin} - {self.year} {self.make} {self.model} - {self.car_type}'

app/salespeople/models.py
import re
from decimal import Decimal
from django.db import models
from django.forms import ValidationError
from django.urls import reverse
from django.core.validators import RegexValidator, validate_email

class Salespeople(models.Model):
    """
    Model for Salespeople instances.
    
    Salespeople instance represents a salesperson in the database. It contains information about the salesperson, including first name, last name, email, phone number, and cars sold by the salesperson.
    
    Attributes:
        first_name (str): The first name of the salesperson.
        last_name (str): The last name of the salesperson.
        email (str): The email address of the salesperson.
        phone_number (str): The phone number of the salesperson.
        sold_cars (list): The list of cars sold by the salesperson.
        
    Methods:
        total_commission: Returns the total commission of the salesperson.
        formatted_commission: Returns the formatted commission of the salesperson.
        total_sales: Returns the total sales of the salesperson.
        total_cars_sold: Returns the total cars sold by the salesperson.
        clean: Validates the salesperson data.
        save: Saves the salesperson data.
        __str__: Returns the string representation of the salesperson.
        get_absolute_url: Returns the absolute URL of the salesperson.
    """
    
    phone_regex = RegexValidator(
        regex = r'^((\d{3}-){2}\d{4})|\d{10}$'
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=17, blank=True)

    def total_commission(self):
        """ Loops through the cars sold and formats each as a decimal. If there is no commision then sets the value as 0.00 ."""
        total = sum(Decimal(car.calculate_commission())
                for car in self.sold_cars.all() if car.sold)
        return total.quantize(Decimal('0.00')) if total != 0 else Decimal('0.00')

    def formatted_commission(self):
        # add commas and format to 2 decimal places
        return "{:,.2f}".format(self.total_commission())

    def total_sales(self):
        """ Loops through the cars sold and formats each price as a decimal and calculates the totals sales. If there is no price then sets the value as 0.00 .  """
        total = sum(Decimal(car.price)
                    for car in self.sold_cars.all() if car.sold)
        return total.quantize(Decimal('0.00')) if total != 0 else Decimal('0.00')
    
    def total_cars_sold(self):
        total = sum(1 for car in self.sold_cars.all() if car.sold)
        return total
    
    def clean(self):
        """
        Validates the Salespeople attributes before saving it to the database. The following validation rules are used:

        Validation Rules:
        1. First and Last name must be unique: 
            - If the first name and last name are already in the database, then raise a validation error.
        2. Email must be unique and correctly formatted.
            - If the email is already in the database, then raise a validation error.
            - If the email is not correctly formatted, then raise a validation error.
        3. Phone number must be unique and correctly formatted.
            - If the phone number is already in the database, then raise a validation error.
            - If it is not in the database, check if it is correctly format and raise and error if it is not.
            
        Args:
            self: The Salespeople instance.
            
        Raises:
            ValidationError: If the validation rules are not met.
        """
        if self.first_name and self.last_name:
            if Salespeople.objects.filter(first_name__iexact=self.first_name, last_name__iexact=self.last_name).exclude(id=self.id).exists():
                raise ValidationError("Salesperson already exists")
            
        if self.email:
            if Salespeople.objects.filter(email__iexact=self.email).exclude(id=self.id).exists():
                raise ValidationError("Email already exists")

            try:
                validate_email(self.email)
            except ValidationError:
                raise ValidationError("Invalid email format")

        if self.phone_number:
            if Salespeople.objects.filter(phone_number__iexact=self.phone_number).exclude(id=self.id).exists():
                raise ValidationError("Phone number already exists")

            try:
                validate_phone_number = self.phone_regex(self.phone_number)
            except ValidationError:
                raise ValidationError("Invalid phone number format. Please use 9192129999 or 999-999-9999 format")
            
    def save(self, *args, **kwargs):
        """
        Saves the Salespeople instance to the database.
        
        This method calls the clean() method to validate the salespeople data. If the data is valid it capitalizes the first and last names and saves the Salespeople instance by calling the save() 
        method of the superclass and passing in *args and **kwargs to ensure that the custom logic and default saving behavior are applied when saving a Salespeople instance. If the data contains a
        hyphen it will split the string on hyphens and spaces, capitalize the first letter of each part, and join them back together. And handles instances where the last name starts with 'Mc'.
        
        Args:
            self: The Salespeople instance.
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
            
        Returns:
            None
        """
        self.clean()

    def custom_capitalize(self, s):
        # Function to handle 'Mc' names
        def mc_name(name):
            if name.lower().startswith('mc') and len(name) > 2:
                return 'Mc' + name[2].upper() + name[3:].lower()
            else:
                return name.capitalize()

        # Split on hyphens and spaces for regular capitalization
        parts = re.split(r'[-\s]', s)
        capitalized_parts = [mc_name(part) for part in parts]
        return '-'.join(capitalized_parts) if '-' in s else ' '.join(capitalized_parts)

    def save(self, *args, **kwargs):
        for field_name in ['first_name', 'last_name']:
            val = getattr(self, field_name, "").strip()
            if val:
                setattr(self, field_name, self.custom_capitalize(val))

        super(Salespeople, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    """ Update the salesperson detail view to show the cars sold by the salesperson """
    def get_absolute_url(self):
        return reverse('salespeople_new', args=[str(self.id)])

app/cars/templates/cars/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    {% load static %}
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous" />
    <!-- Favions -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}?v=1"> <!-- Add this line to load the CSS file -->
    <title>{% block title %}Car Dealership{% endblock %}</title>
    {% block extrahead %} {% endblock %}
    <!-- Bootstrap Core JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
    integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
    crossorigin="anonymous"></script>
</head>


<body class="bg-dark">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top mb-1">
        <div class="container">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Navbar Links -->
            <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
                <ul class="navbar-nav"> <!-- 'ml-auto' to align the menu items to the right -->
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'car_list' %}"><i class="fa fa-info fa-lg"></i> Vehicles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'salespeople_list' %}">Salespeople</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="body-content">{% block content %}{% endblock content %}</div>
    <footer class="page-footer font-small py-0">           
        <div class="text-center">
            <p class="text-light small-print mb-0">
                &copy; <span id="current-year"></span> Pia Torain. All rights reserved.
            </p>
        </div>
    </footer>
    {% block jsfiles %}
        <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                document.getElementById('current-year').textContent = new Date().getFullYear();
            });
        </script>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                var footer = document.querySelector('.page-footer');
                var fixedFooterPages = ['/cars/', '/cars/new/', '/salespeople/'];

                if (fixedFooterPages.includes(window.location.pathname)) {
                    footer.classList.remove('fixed-bottom');
                } 
            });
        </script>
    {% endblock jsfiles %}
</body>


</html>

app/cars/templates/cars/car_confirm_delete.html
{% extends "cars/car_list.html" %}

{% block title %}Confirm Delete Car{% endblock %}

{% block content %}
    <div class="container text-center bg-dark py-4">
        <h2 class="fw-bold text-warning my-3">WARNING!<br> THIS ACTION CANNOT BE REVERSED</h2>
        <h3 class="fw-bold text-light">Are you sure you want to delete this vehicle?</h3>
        <h3 class="text-danger my-2">{{ object }}</h3>

        <form method="post" class="my-4">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete</button>
        {% url 'car_list' as car_list_url %}
        {% if request.path == car_list_url %}
            <a href="{{ car_list_url }}" class="btn btn-secondary">Cancel</a>
        {% else %}
            <a href="{% url 'car_detail' object.id %}" class="btn btn-secondary">Cancel</a>
        {% endif %}
        </form>
    </div>
{% endblock %}

app/cars/templates/cars/car_detail.html
{% extends "cars/car_list.html" %}

{% load static %}

{% block title %}Car Details{% endblock %}

{% block content %}
<div class="container text-light">
    <h2>Car Details</h2>
    <div class="car-detail-container row">
        <div class="car-details">
            <p><strong>VIN:</strong> {{ car.vin }}</p>
            <p><strong>Make:</strong> {{ car.make }}</p>
            <p><strong>Model:</strong> {{ car.model }}</p>
            <p><strong>Year:</strong> {{ car.year }}</p>
            <p><strong>Color:</strong> {{ car.get_car_color_display}}</p>
            <p><strong>Price:</strong> ${{ car.formatted_price }}</p>
            <p><strong>Mileage:</strong> {{ car.formatted_mileage }}</p>
            <p><strong>Sold:</strong> {{ car.sold }}</p>
            <p><strong>Date Sold:</strong> {{ car.date_sold }}</p>

            {% if car.salesperson %}
            <p><strong>Salesperson:</strong>
                <a href="{% url 'salespeople_detail' car.salesperson.id %}">
                    {{ car.salesperson.first_name }} {{ car.salesperson.last_name}}
                </a>
            </p>
            {% endif %}

            <p><strong>Type:</strong> {{ car.get_car_type_display }}</p>
        </div>
        <div class="car-image col-md-8">
            {% if car.car_type == 'SUV' and car.car_color == 'Black'%}
                <img src="{% static 'images/bl-suv.png' %}" alt="SUV " class="img-fluid">
            {% elif car.car_type == 'Truck' and car.car_color == 'Black'%}
                <img src="{% static 'images/bk_pu.png' %}" alt="Pickup Truck " class="img-fluid">
            {% elif car.car_type == 'Sedan' and car.car_color == 'Black'%}
                <img src="{% static 'images/bk_car.png' %}" alt="Black Sedan" class="img-fluid">
            {% elif car.car_type == 'Convertible' and car.car_color == 'Black'%}
                <img src="{% static 'images/bl_con.png' %}" alt="Convertible" class="img-fluid">
            {% elif car.car_type == 'Truck' and car.car_color == 'Blue'%}
                <img src="{% static 'images/blue_pu.png' %}" alt="Blue Pickup Truck " class="img-fluid">
            {% elif car.car_type == 'Sedan' and car.car_color == 'Blue'%}
                <img src="{% static 'images/bu_car.png' %}" alt="Blue Sedan class="img-fluid">
            {% elif car.car_type == 'Convertible' and car.car_color == 'Blue'%}
                <img src="{% static 'images/bu_con.png' %}" alt="Blue Convertible" class="img-fluid">
            {% elif car.car_type == 'Coupe' and car.car_color == 'Blue'%}
                <img src="{% static 'images/bu_hb.png' %}" alt="Blue Coupe" class="img-fluid">
            {% elif car.car_type == 'Sedan' and car.car_color == 'Red'%}
                <img src="{% static 'images/rd_car.png' %}" alt="Red Sedan class="img-fluid">
            {% elif car.car_type == 'Convertible' and car.car_color == 'Red'%}
                <img src="{% static 'images/rd_con.png' %}" alt="Red Convertible" class="img-fluid">
            {% elif car.car_type == 'Truck' and car.car_color == 'Red'%}
                <img src="{% static 'images/rd_pu.png' %}" alt="Red Pickup Truck" class="img-fluid">
            {% elif car.car_type == 'Sedan' and car.car_color == 'Silver'%}
                <img src="{% static 'images/sil_car.png' %}" alt="Silver Convertible" class="img-fluid">
            {% elif car.car_type == 'Truck' and car.car_color == 'Silver'%}
                <img src="{% static 'images/sil_pu.png' %}" alt="Silver Pickup" class="img-fluid">
            {% elif car.car_type == 'Sedan' and car.car_color == 'Orange'%}
                <img src="{% static 'images/or_car.png' %}" alt="Orange Sedan" class="img-fluid">
            {% elif car.car_type == 'SUV' and car.car_color == 'Orange'%}
                <img src="{% static 'images/or_suv.png' %}" alt="Orange SUV" class="img-fluid">
            {% elif car.car_type == 'SUV'%}
                <img src="{% static 'images/suv.svg' %}" alt="SUV" class="img-fluid py-3">
            {% elif car.car_type == 'Truck' %}
                <img src="{% static 'images/pickup.png' %}" alt="Default Pickup Truck" class="img-fluid">
            {% elif car.car_type == 'Convertible' %}
                <img src="{% static 'images/con.png' %}" alt="Default Convertible" class="img-fluid">
            {% else %}
                <img src="{% static 'images/cd.png' %}" alt="Default Car" class="img-fluid default-img p-2">
            {% endif %}
            {% if car.car_type %}
                <p class="text-center text-warning img-text">Generic stock image. {{car.car_color}} {{car.make}} {{car.model}} coming
                    soon.</p>
            {% endif %}
        </div>

    </div>
    <div class="row">
        <div class="d-flex flex-row justify-content-between">
            <div class="mb-2 mb-md-0">
                <a href="{% url 'car_edit' car.id %}" class="btn btn-primary me-2 mb-2 ">Edit</a>
                <a href="{% url 'car_delete' car.id %}" class="btn btn-danger mb-2">Delete</a>
            </div>
            <div class="">
                <a href="{% url 'car_list' %}" class="btn btn-secondary me-2 mb-2 ">Back to List</a>
                <!-- Check if the car has an associated salesperson -->
                {% if car.salesperson %}
                <a href="{% url 'salespeople_detail' car.salesperson.id %}" class="btn btn-secondary mb-2 ">Salesperson</a>
                {% else %}
                <span class="btn btn-secondary mb-2 disabled">No Salesperson</span>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

app/cars/templates/cars/car_form.html
{% extends 'cars/car_list.html' %}

{% block content %}
<div class="container text-light">
    <h2 class="my-3">{% if object %}Edit{% else %}Add{% endif %} Car</h2>

    <form method="post" class="border border-start-0 border-end-0 border-bottom-0 border-info py-3">
        {% csrf_token %}

        <!-- Display non-field-specific errors -->
        {% if form.non_field_errors %}
        <div class="alert alert-danger">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>
        {% endif %}

        <!-- Display field-specific errors and fields -->
        {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {% if field.name == 'date_sold' %}
            {{ field }} 
            {% else %}
            {{ field }}
            {% endif %}
            {% if field.errors %}
        <div class="alert alert-danger">
            {% for error in field.errors %}
            {{ error }}
            {% endfor %}
        </div>
        {% endif %}
        </p>
        {% endfor %}

        <button type="submit" class="btn btn-primary">{% if object %}Update{% else %}Create{% endif %} Car</button>
        <a href="{% url 'car_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>

<!-- Include flatpickr CSS and JS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<style>
    .flatpickr-alt,
    .form-control {
        box-sizing: border-box;
        max-width: 167px;
    }
</style>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        flatpickr("input[name='date_sold']", {
            dateFormat: "Y-m-d", // Set the date format to YYYY-MM-DD
            altInput: true, // Display the date in the altInput field
            altFormat: "Y-m-d", // Set the altInput date format to Month Day, Year
            altInputClass: "form-control", // Add the form-control class to the altInput field
        });
    });
</script>
{% endblock %}

app/cars/templates/cars/index.html
{% extends "cars/base.html" %} 
{% load static %}
{% block title %} Car Dealership {% endblock%} 

{% block content%}
    <div class="container-flex text-light text-center my-5 my-md-1 p-3 py-md-0">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 my-2 mb-5 title-holder">
                <h1 class="display-1 title">Car Dealership</h1>
                <h3 class="title">An inventory and sales management system</h3>
            </div>
            <div class="col-12 col-md-8 p-0 my-5">
                <img src="{% static 'images/car-home.svg' %}" alt="Car Dealership" class="img-fluid">
            </div>
        </div>
    </div>

{% endblock %} 
{% block jsfiles %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            document.getElementById('current-year').textContent = new Date().getFullYear();
        });
    </script>
{% endblock jsfiles %}